production:
  access_key_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  secret_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  bucket: redhero-prod
  endpoint:
  secure:
  private:
  expires:

development:
  access_key_id: xxxxxxxxxxxxxxxxxxxxxxxxx
  secret_access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  bucket: redhero-prod
  endpoint:
  secure:
  private:
  expires: 
